### ISSUE TITLE
"ImproperlyConfigured: Could not resolve URL for hyperlinked relationship"...

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/api#39]
Interesting error here:

>ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "dataset-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

You can see this error on my latest `lukeswart/django18-drf3` branch. 

I suspect this is related to some changes to the `hyperlinkedModelSerializer`, listed here: http://www.django-rest-framework.org/topics/3.0-announcement/#changes-to-hyperlinkedmodelserializer

Here is the stacktrace of the first error:

```
.......................F..F........................FFFF...FFFFFFFFF.........FFFF.EEFEFFFFFFFFFFF.FFFFFEEEE...EEE.EEEE.EFFFEFFF.FFFFFFFF.EEEEEFFFFFEEEE.E.EEEFFF.FFFF.EEEE.EFFE
======================================================================
ERROR: test_GET_response (sa_api_v2.tests.test_views.TestDataSetInstanceView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/me/projects/SmarterCleanup/smartercleanup-api/src/sa_api_v2/tests/test_views.py", line 3196, in test_GET_response
    response = self.view(request, **self.request_kwargs)
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/me/projects/SmarterCleanup/smartercleanup-api/src/sa_api_v2/views/base_views.py", line 582, in dispatch
    return super(OwnedResourceMixin, self).dispatch(request, *args, **kwargs)
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/rest_framework/generics.py", line 286, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/rest_framework/mixins.py", line 58, in retrieve
    return Response(serializer.data)
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/rest_framework/serializers.py", line 503, in data
    ret = super(Serializer, self).data
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/rest_framework/serializers.py", line 472, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/me/.virtualenvs/smartercleanup-api-1.8/lib/python2.7/site-packages/rest_framework/relations.py", line 366, in to_representation
    raise ImproperlyConfigured(msg % self.view_name)
ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "dataset-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
-------------------- >> begin captured logging << --------------------
sa_api_v2.cache: DEBUG: Keys with prefixes "": ""
sa_api_v2.cache: DEBUG: Deleting: "UserCache:78:_keys", "UserCache:78", "user-instance:78"
sa_api_v2.cache: DEBUG: Keys with prefixes "": ""
sa_api_v2.cache: DEBUG: Deleting: "UserCache:79:_keys", "UserCache:79", "user-instance:79"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds": "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys"
sa_api_v2.cache: DEBUG: Deleting: "dataset-instance:aaron:ds", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "DataSetCache:46", "DataSetCache:46:_keys", "dataset-permissions:aaron:ds"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds": "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys"
sa_api_v2.cache: DEBUG: Deleting: "dataset-instance:aaron:ds", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "DataSetCache:46", "DataSetCache:46:_keys", "dataset-permissions:aaron:ds"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/92", "/api/v2/aaron/datasets/ds/actions": "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys"
sa_api_v2.cache: DEBUG: Deleting: "PlaceCache:92:_keys", "PlaceCache:92", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds/places/92/comments", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/92/submissions/93", "/api/v2/aaron/datasets/ds/places/92", "/api/v2/aaron/datasets/ds/places/92/submissions", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/comments", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/places/92/comments/93": "/api/v2/aaron/datasets/ds/comments_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/93_keys", "/api/v2/aaron/datasets/ds/places/92/comments/93_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places/92/comments_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/comments_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/93_keys", "/api/v2/aaron/datasets/ds/places/92/comments/93_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "SubmissionCache:93", "/api/v2/aaron/datasets/ds/places_keys", "PlaceCache:92:_keys", "/api/v2/aaron/datasets/ds/places/92/comments_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "SubmissionCache:93:_keys", "DataSetCache:46:_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds/places/92/comments", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/92/submissions/94", "/api/v2/aaron/datasets/ds/places/92", "/api/v2/aaron/datasets/ds/places/92/submissions", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/comments", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/places/92/comments/94": "/api/v2/aaron/datasets/ds/comments_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/94_keys", "/api/v2/aaron/datasets/ds/places/92/comments_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/comments/94_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/comments_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/94_keys", "PlaceCache:92:_keys", "/api/v2/aaron/datasets/ds/places/92/comments_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/comments/94_keys", "SubmissionCache:94:_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "DataSetCache:46:_keys", "SubmissionCache:94"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds/places/92/comments", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/92/submissions/95", "/api/v2/aaron/datasets/ds/places/92", "/api/v2/aaron/datasets/ds/places/92/submissions", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/comments", "/api/v2/aaron/datasets/ds/places/92/comments/95", "/api/v2/aaron/datasets/ds/places": "/api/v2/aaron/datasets/ds/comments_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places/92/comments/95_keys", "/api/v2/aaron/datasets/ds/places/92/comments_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/95_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/comments_keys", "SubmissionCache:95", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "PlaceCache:92:_keys", "/api/v2/aaron/datasets/ds/places/92/comments/95_keys", "/api/v2/aaron/datasets/ds/places/92/comments_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/95_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "SubmissionCache:95:_keys", "/api/v2/aaron/datasets/ds/places_keys", "DataSetCache:46:_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/92/likes", "/api/v2/aaron/datasets/ds/places/92/submissions/96", "/api/v2/aaron/datasets/ds/places/92", "/api/v2/aaron/datasets/ds/places/92/submissions", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/likes", "/api/v2/aaron/datasets/ds/places/92/likes/96": "/api/v2/aaron/datasets/ds/places/92/likes_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/96_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places/92/likes/96_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/places/92/likes_keys", "SubmissionCache:96", "/api/v2/aaron/datasets/ds/places/92/submissions/96_keys", "SubmissionCache:96:_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places/92/likes/96_keys", "PlaceCache:92:_keys", "DataSetCache:46:_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/places/92/submissions/97", "/api/v2/aaron/datasets/ds/places/92", "/api/v2/aaron/datasets/ds/places/92/submissions", "/api/v2/aaron/datasets/ds/places/92/likes", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/likes", "/api/v2/aaron/datasets/ds/places/92/likes/97": "/api/v2/aaron/datasets/ds/places/92/likes_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/likes_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places/92/likes/97_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/97_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/places/92/likes_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "SubmissionCache:97", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "DataSetCache:46:_keys", "PlaceCache:92:_keys", "/api/v2/aaron/datasets/ds/likes_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "SubmissionCache:97:_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places/92/likes/97_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/97_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds/places/92/submissions", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/places/92/submissions/98", "/api/v2/aaron/datasets/ds/places/92", "/api/v2/aaron/datasets/ds/places/92/likes/98", "/api/v2/aaron/datasets/ds/places/92/likes", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/likes": "/api/v2/aaron/datasets/ds/places/92/likes_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/98_keys", "/api/v2/aaron/datasets/ds/places/92/likes/98_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/places/92/likes_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places_keys", "PlaceCache:92:_keys", "DataSetCache:46:_keys", "SubmissionCache:98:_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/98_keys", "/api/v2/aaron/datasets/ds/places/92/likes/98_keys", "/api/v2/aaron/datasets/ds/likes_keys", "SubmissionCache:98"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds/places/92/likes", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/92/submissions/99", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/places/92", "/api/v2/aaron/datasets/ds/places/92/submissions", "/api/v2/aaron/datasets/ds/places/92/likes/99", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/likes": "/api/v2/aaron/datasets/ds/places/92/likes_keys", "/api/v2/aaron/datasets/ds/places/92/likes/99_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/99_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/places/92/likes_keys", "SubmissionCache:99", "/api/v2/aaron/datasets/ds/places/92/likes/99_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/92_keys", "PlaceCache:92:_keys", "/api/v2/aaron/datasets/ds/places/92/submissions/99_keys", "DataSetCache:46:_keys", "/api/v2/aaron/datasets_keys", "SubmissionCache:99:_keys", "/api/v2/aaron/datasets/ds/places/92/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds/places/100", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places": "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/places/100_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/100_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "PlaceCache:100", "PlaceCache:100:_keys", "/api/v2/aaron/datasets/ds/places_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds": "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys"
sa_api_v2.cache: DEBUG: Deleting: "dataset-instance:aaron:ds", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "DataSetCache:46", "DataSetCache:46:_keys", "dataset-permissions:aaron:ds"
oauthlib.oauth2.rfc6749.endpoints.resource: DEBUG: Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x7f41fbc26b90>.
--------------------- >> end captured logging << ---------------------
```

**Comment by LukeSwart** [comment]
Fixed in PR #43
